version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    networks:
      - main
    ports:
      - "54321:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: {}

networks:
  main:
    driver: bridge