version: "3.8"

services:

  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    networks:
      - main

volumes:
  db:
    driver: local

networks:
  main:
    driver: bridge